  -- 1. Create a bucket table to hold the raw file data
   CREATE TABLE raw_json_load (
       id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
       raw_doc CLOB,
       CONSTRAINT ensure_json CHECK (raw_doc IS JSON)
   );

   -- 2. Create the structured relational destination table
   CREATE TABLE spotify_json_staging (
       timestamp_str VARCHAR2(50),
       platform      VARCHAR2(100),
       ms_played     NUMBER,
       country       VARCHAR2(10),
       track_name    VARCHAR2(255),
       artist_name   VARCHAR2(255),
       album_name    VARCHAR2(255),
       reason_start  VARCHAR2(50),
       reason_end    VARCHAR2(50),
       shuffle       VARCHAR2(10),
       skipped       VARCHAR2(10)
   );

   -- 3.Verify Results
-- Confirm raw_json_load structure exists and is empty before loading
SELECT COUNT(*) FROM raw_json_load;

-- Confirm spotify_json_staging structure is in place
SELECT COUNT(*) FROM spotify_json_staging;
