-- ============================================================================
-- 1. DIMENSION & FACT TABLE STRUCTURES
-- ============================================================================

-- Drop tables in topological order (Fact first, then Dimensions)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables 
              WHERE table_name IN ('FACT_STREAMING_HISTORY', 'DIM_SONGS', 'DIM_PLATFORMS', 'DIM_ALBUMS')) 
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- Dimension 1: Albums & Eras
CREATE TABLE dim_albums (
    album_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_name      VARCHAR2(100) NOT NULL,
    release_year    NUMBER(4),
    era             VARCHAR2(50),
    total_tracks    NUMBER,
    created_at      DATE DEFAULT SYSDATE,
    CONSTRAINT chk_release_year CHECK (release_year BETWEEN 1900 AND 2100)
);

-- Dimension 2: Deduplicated Songs / Tracks
CREATE TABLE dim_songs (
    song_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_name      VARCHAR2(200) NOT NULL,
    album_id        NUMBER CONSTRAINT fk_songs_album REFERENCES dim_albums(album_id),
    duration_ms     NUMBER NOT NULL,
    track_number    NUMBER,
    is_explicit     CHAR(1) DEFAULT 'N',
    CONSTRAINT chk_songs_explicit CHECK (is_explicit IN ('Y', 'N'))
);

-- Dimension 3: Client Platforms & Operating Systems
CREATE TABLE dim_platforms (
    platform_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_platform    VARCHAR2(100) NOT NULL UNIQUE,
    clean_platform  VARCHAR2(30)  NOT NULL, -- mobile / desktop / web / partner
    os_name         VARCHAR2(30)            -- OS X, iOS, Windows, Chrome
);

-- Fact Table: Granular Streaming Events
CREATE TABLE fact_streaming_history (
    stream_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    song_id         NUMBER NOT NULL CONSTRAINT fk_fact_song REFERENCES dim_songs(song_id),
    album_id        NUMBER NOT NULL CONSTRAINT fk_fact_album REFERENCES dim_albums(album_id),
    platform_id     NUMBER NOT NULL CONSTRAINT fk_fact_platform REFERENCES dim_platforms(platform_id),
    played_at       TIMESTAMP(6) NOT NULL,
    play_date       DATE NOT NULL, -- Date key for optimized BI calendar alignment
    ms_played       NUMBER NOT NULL,
    minutes_played  NUMBER(10,3) GENERATED ALWAYS AS (ROUND(ms_played / 60000, 3)),
    skipped_flag    NUMBER(1) NOT NULL,
    shuffle_flag    NUMBER(1) NOT NULL,
    CONSTRAINT chk_skipped_bin CHECK (skipped_flag IN (0, 1)),
    CONSTRAINT chk_shuffle_bin CHECK (shuffle_flag IN (0, 1))
)
PARTITION BY RANGE (play_date) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) (
    PARTITION p_init VALUES LESS THAN (TO_DATE('2021-01-01', 'YYYY-MM-DD'))
);

-- B-Tree Performance Indexes for BI Star Queries
CREATE INDEX idx_fact_play_date ON fact_streaming_history(play_date);
CREATE INDEX idx_fact_song_fk   ON fact_streaming_history(song_id);
CREATE INDEX idx_fact_album_fk  ON fact_streaming_history(album_id);
CREATE INDEX idx_songs_search   ON dim_songs(UPPER(track_name));
/


-- ============================================================================
-- 2. STAR SCHEMA TOPOLOGY
-- ============================================================================

WITH mock_metadata AS (

    -- FACT TABLE → DIMENSIONS
    SELECT
        'FACT_STREAMING_HISTORY' AS table_name,
        'FK_FACT_SONG'           AS constraint_name,
        'DIM_SONGS'              AS parent_table
    FROM dual

    UNION ALL

    SELECT
        'FACT_STREAMING_HISTORY',
        'FK_FACT_ALBUM',
        'DIM_ALBUMS'
    FROM dual

    UNION ALL

    SELECT
        'FACT_STREAMING_HISTORY',
        'FK_FACT_PLATFORM',
        'DIM_PLATFORMS'
    FROM dual

    -- DIMENSION → DIMENSION
    UNION ALL

    SELECT
        'DIM_SONGS',
        'FK_SONGS_ALBUM',
        'DIM_ALBUMS'
    FROM dual
),

schema_tree (
    table_name,
    constraint_name,
    parent_table,
    hierarchy_level,
    topology
) AS (

    -- ========================================================================
    -- ROOT: FACT TABLE
    -- ========================================================================

    SELECT
        'FACT_STREAMING_HISTORY',
        NULL,
        NULL,
        1,
        '⭐ [FACT] FACT_STREAMING_HISTORY'
    FROM dual

    UNION ALL

    -- ========================================================================
    -- CHILDREN: DIMENSIONS
    -- ========================================================================

    SELECT
        m.parent_table,
        m.constraint_name,
        m.table_name,
        st.hierarchy_level + 1,

        CASE
            WHEN st.hierarchy_level = 1 THEN
                '    └── 📐 [DIMENSION] ' ||
                m.parent_table ||
                ' (via ' ||
                m.constraint_name ||
                ')'

            ELSE
                '        └── 📐 [DIMENSION] ' ||
                m.parent_table ||
                ' (via ' ||
                m.constraint_name ||
                ')'
        END

    FROM schema_tree st
    JOIN mock_metadata m
        ON m.table_name = st.table_name
)

SELECT topology AS star_schema_topology
FROM schema_tree
ORDER BY hierarchy_level, topology;

